language: csharp
solution: Fos.sln
install:
  - nuget restore Fos.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Fos.sln
  - mono ./testrunner/NUnit.Console.3.7.0/tools/nunit-console.exe ./Fos.Tests/bin/Release/Fos.Tests.dll